<?php
namespace Tenweb_Builder;

include_once TWBB_DIR . '/templates/base.php';

class SingleTemplate extends BaseTemplate {

  public static function get_slug(){
    return "twbb_single";
  }

  public static function get_title(){
    return 'Single';
  }


  public function save_type(){
    parent::save_type(); // TODO: Change the autogenerated stub
	//phpcs:ignore WordPress.Security.NonceVerification.Recommended
    if(!empty($_REQUEST['twbb-template-post-type'])) {
      //phpcs:ignore WordPress.Security.NonceVerification.Recommended
      $meta_value = sanitize_text_field($_REQUEST['twbb-template-post-type']);
      $this->update_meta('_twbb-template-post-type', $meta_value);
    }

  }

	public static function print_twbb_template($template_id, $templates = "") {
		// ( 'twbb_archive' === Templates::get_instance()->get_current_template_type() ) to edit archive template as single.
		if( ( \Elementor\Plugin::instance()->preview->is_preview_mode() && static::current_template() ) || ( 'twbb_archive' === Templates::get_instance()->get_current_template_type() ) || ( 'twbb_archive_products' === Templates::get_instance()->get_current_template_type() ) || ( 'twbb_single_product' === Templates::get_instance()->get_current_template_type() ) || ( 'twbb_slide' === Templates::get_instance()->get_current_template_type() ) ) {
            //phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped
			echo \Elementor\Plugin::instance()->preview->builder_wrapper('');
		} else {
			self::print_builder_content($template_id);
		}
	}

}
